app/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('books/', views.BookListView.as_view(), name='books'),
	path('book/<slug>', views.book_detail, name='book-detail'),
	path('authors/', views.AuthorListView.as_view(), name='authors'),
	path('authors/<slug>', views.AuthorDetailView.as_view(), name='author-detail'),
	path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
	path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
	path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<slug>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<slug>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
	path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<slug>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<slug>/delete/', views.BookDelete.as_view(), name='book_delete'),
    path('search/', views.search_screen_view, name='search'),
    path('borrowed/', views.BooksBorrowed.as_view(), name='borrowed'),
]

app/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from datetime import date
import uuid

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    slug = models.SlugField(max_length=255, blank=True, unique=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

def genre_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

pre_save.connect(genre_pre_save_receiver, sender=Genre)

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")
    slug = models.SlugField(max_length=8, blank=True, unique=True)
    
    def __str__(self):
    	return self.name

def language_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.name and instance.slug:
        lang_dict = dict(settings.LANGUAGES)
        instance.name = lang_dict[instance.slug]

    if not instance.slug and instance.name:
        lang_dict = dict(settings.LANGUAGES)
        invert_dict = dict((v, k) for k, v in lang_dict.items())
        instance.slug = invert_dict[instance.name]

pre_save.connect(language_pre_save_reciever, sender=Language)

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    image = models.CharField('Image URL', default='', max_length=1024, help_text='Book cover image link')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.slug)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

def book_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)

pre_save.connect(book_pre_save_reciever, sender=Book)

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='borrower')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='owner')

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)
    slug = models.SlugField(max_length=255, blank=True, unique=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.slug)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

def author_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify("%s-%s" %(instance.first_name, instance.last_name))

pre_save.connect(author_pre_save_reciever, sender=Author)

app/catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

app/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from operator import attrgetter
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from catalog.forms import RenewBookForm
from django.views import generic
from catalog.models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from catalog.models import Author
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")

def display_service(text):
    doc = nlp(text)
    html = displacy.render(doc, style="ent", page=False)
    return html;

def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    pos = display_service(book.summary)
    # print(pos)

    return render(request, "catalog/book_detail.html", { "book": book, "pos": pos })

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('my-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}

class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    fields = '__all__'

class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']

class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_mark_returned'

class BooksBorrowed(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name ='catalog/list_borrowed.html'
    paginate_by = 10

def get_book_queryset(query=None):
    queryset = []
    queries = query.split(' ') # python install 2019 = ['python', 'install', '2019']
    for q in queries:
        posts = Book.objects.filter(Q(title__contains=q)| Q(summary__icontains=q) ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))

def search_screen_view(request):
    context = {}

    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    books = sorted(get_book_queryset(query), key=attrgetter('title'), reverse=True)

    context['books'] = books

    return render(request, 'catalog/search.html', context)

app/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Delete Author</h2>

<p>Are you sure you want to remove the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Do you really want to remove this Author?" class="btn btn-primary">
</form>

{% endblock %}

app/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
  <div>
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    {% if perms.catalog.can_mark_returned %}  
      <a href="{% url 'author_update' author.pk %}" class="btn btn-primary">Update</a>
      <a href="{% url 'author_delete' author.pk %}" class="btn btn-primary">Remove</a>
    {% endif %} 
    <br>
    <br>
    <div>
    {% for book in author.book_set.all %}
      <a href="{% url 'book-detail' book.slug %}"><h5 class="livro">{{book}} ({{book.bookinstance_set.all.count}})</h5></a> 
      <dd>{{book.summary}}</dd>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

app/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post" class="form-group mt-3">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary mt-3">
  </form>
{% endblock %}

app/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
      <h2>Authors</h2>
      <br>
      {% if author_list %}
      <ul class="list-group">
        {% for author in author_list %}
          <li class="list-group-item">
            <p><strong>Author:</strong> <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a></p>
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>There are no books in the library.</p>
      {% endif %}  
</div>  
{% endblock %}

app/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Delete Book</h2>

<p>Are you sure you want to remove the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Do you really want to remove this book?" class="btn btn-primary">
</form>

{% endblock %}

app/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
  <h2>{{ book.title }}</h2>
  <img src="{{ book.image }}" class="skull img-thumbnail" style="width:250px;height:'100%';">
  <br>
  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.slug %}">{{ book.author }}</a></p> 
  {% autoescape off %}
    {{ pos }}
  {% endautoescape %}
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genres:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  {% if perms.catalog.can_mark_returned %}  
    <a href="{% url 'book_update' book.slug %}" class="btn btn-primary">Update</a>
    <a href="{% url 'book_delete' book.slug %}" class="btn btn-primary">Remove</a>
  {% endif %} 
  <div>
    <hr>
    <h4>Copies:</h4>
    {% for copy in book.bookinstance_set.all %}
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post" class="form-group mt-3">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary mt-3">
  </form>
{% endblock %}

app/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
      <h2>Books</h2>
      <form method="GET" action="{% url 'search' %}">
          <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
      </form>
      <br>
      {% if book_list %}
      <ul class="list-group">
        {% for book in book_list %}
          <li class="list-group-item">
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>There are no books in the library.</p>
      {% endif %}  
</div>  
{% endblock %}

app/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Renew: {{ book_instance.book.title }}</h3>
  <p>Borrower: <strong>{{ book_instance.borrower }}</strong></p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due back: <strong>{{ book_instance.due_back }}</strong></p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

app/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h4>My Books</h4>
    <br>
    {% if bookinstance_list %}
    <ul class="list-group">
      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %} list-group-item">
        <a href="{% url 'book-detail' bookinst.book.slug %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}        
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>You currently have no borrowed books.</p>
    {% endif %} 
</div>      
{% endblock %}

app/catalog/templates/catalog/list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h4>Bookshelf</h4>
    <br>
    {% if bookinstance_list %}
    <ul class="list-group">
      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %} list-group-item">
        <a href="{% url 'book-detail' bookinst.book.slug %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }}
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>You currently have no borrowed books.</p>
    {% endif %} 
</div>      
{% endblock %}

app/catalog/templates/catalog/search.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
      <h2>Books</h2>
      <form method="GET">
          <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
      </form>
      <br>
      {% if books %}
      <ul class="list-group">
        {% for book in books %}
          <li class="list-group-item">
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
            <p>{{ book.summary }}</p>
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>Book not found.</p>
      {% endif %}  
</div>  
{% endblock %}